services:
  linkshortenerapi:
    build:
      context: ./LinkShortenerAPI  # Points to the directory containing the Dockerfile
      dockerfile: Dockerfile       # Optional: If the Dockerfile is named differently
    container_name: linkshortener-api
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=db;port=3306;database=mydatabase;user=myuser;password=mypassword;

  db:
    image: mysql:latest
    container_name: mysql-link-shortener-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
