version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linkshortener-api
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=db;port=3306;database=mydatabase;user=myuser;password=mypassword;
    # Optional: You can also use a retry mechanism or health check here for the API.

  db:
    image: mysql:latest
    container_name: mysql-link-shortener-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  db_data:
